### ISSUE TITLE
Updating CONTRIBUTING.md with more developer guidelines

### ISSUE THREAD

**Issue by Ramblurr** [katharsis-project/katharsis-framework#243]
## Background

The current [CONTRIBUTING document](https://github.com/katharsis-project/katharsis-framework/commit/3d81ef228be6c8c303ebc50a39f0784d1f28007c) is in draft state and needs to be updated.

Also I've noticed a discrepancy in code-style across all the modules. Most files use spaces, but some use tabs. The import order varies wildly. There are some other few discrepancies as well.

These discrepancies will only continue to grow the more developers we add to the project. One nasty side affect of different code styles, is that pull requests have lots of *noise* in the form of import order changes, whitespace changes, etc. 
## Proposal

This can all be nipped in the bud by specifying an official Katharsis project formatter for Eclipse and IntelliJ.

Most of the developers are already using the same style, in theory, so there is no reason to change. The only settings that need tweaking or whitespace and import order. 

While at it we can spruce of the Contribution guidelines and specify default ISSUE and PR templates to encourage correct and useful contributes from the community.

### TODO

If everyon is in agreement then we can:

- [ ] Provide importable formatter settings for Eclipse and Intellij
- [ ] Apply the new formatter across the entire project to normalize our still from here on out
- [ ] Update Contribution guidelines and add project issue and PR templates

**Comment by Ramblurr** [comment]
I don't have an opinion on tabs or spaces, my vote is for whatever the consensus is.

**Comment by remmeier** [comment]
we may put the formatting into maven itself as a step. Eclipse, Intellj, etc. can be configured to look quite a like, but they still differ. Code formatter configurations for Eclipse and Intellij nevertheless would be helpful.

**Comment by Ramblurr** [comment]
@remmeier Any comment on tabs/space and import order?

It's true Eclipse and IDEA differ, but not on the most common source of PR noise: import order and whitespace. If lock down those settings, and then everyone runs the formatter on just the *changed* lines ([intellij](http://adm-10980.intellij.net/zendesk-forum-storage/jc/5460198/reformat.png) [eclipse](http://eclipsesource.com/blogs/wp-content/uploads/2012/10/9.png), then we'll be good. Actually... I will add these to the PR.

The configs I'm building are taken from the spring-data projects [own config](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide), they require it in their [CONTRIBUTING](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).

**Comment by remmeier** [comment]
import order is ok for me, I'm not really looking at those.

**Comment by chb0github** [comment]
Spaces are more portable than tabs -- 4 spaces I think is the default IJ arrangement.

**Comment by masterspambot** [comment]
Let's don't start battle tabs vs spaces here guys! 🛩

**Comment by Ramblurr** [comment]
@masterspambot I totally agree, I don't want to start an argument, and based on the responses it doesn't seem like anyone is keen on starting it either. But there are different opinions, and we need to come to a consensus.

If we don't then the commits become more noisy as extraneous whitespace changes, or files start getting mixed tabs/spaces.

I'll give this another few days, then see what people have chosen, if there is no consensus I will count the total number of files with tabs and with spaces and choose the one with the largest.

Then I can upload the eclipse + IJ format configs.

**Comment by mohlek** [comment]
Personally I like spaces. Maybe its a good idea to look what IDE is used the most and go with the "default" settings?!

**Comment by masterspambot** [comment]
Two cents from me. Instead of keeping IDE configs in code lets embed formatting/style checking in build process. What do you think about that? This would make us IDE agnostic and enforce code formatting style.

https://github.com/revelc/formatter-maven-plugin
http://www.jillesvangurp.com/2015/01/29/enforcing-code-conventions-in-java/

Personally I am for *tabs*:
http://softwareengineering.stackexchange.com/a/2037

**Comment by remmeier** [comment]
formatting in the build sounds perfect to me.

So far the the tabs seem to be favored. Not uncommon in the Java world I would say.

**Comment by mohlek** [comment]
http://www.jillesvangurp.com/2015/01/29/enforcing-code-conventions-in-java/

this article seems to cover everything we need

**Comment by masterspambot** [comment]
I am glad we came to agreement! 👏 👏

**Comment by chb0github** [comment]
One thing I don't want to get into is a lowest-common-denominator development environment where we use 80-character lines because someone has decided he likes to develop on old mainframes. I have 2x27" displays.

The tool in use doesn't matter too much to me.

BTW: are people really finding the coding format impossible to work with?

**Comment by masterspambot** [comment]
It is often seen in PR @chb0github... That people reformat code in there
and whole file is included.

**Comment by Ramblurr** [comment]
Yes, like @masterspambot said the main problem with not having a project standard is that the PRs and commits are very very noisy as the different IDEs apply formatting to a file when changing only a few lines.

In the slightly worse case the dev might have the IDE to only apply formatting rules to lines they actually change, but this ends up with inconsistent styles as some lines are 80 chars with spaces and others are 100 with tabs and all `{` on new lines.

I'll  setup that maven plugin and see if it behaves sanely.

(also, I'm for longer lines too.)
